root:
  ./docs/
redirects:
  pantry: pantry.md
  shell-integration: shell-integration.md
  shellcode: shell-integration.md
  getting-started: run/anywhere/terminals.md
  quickstart: run/anywhere/terminals.md
  installing-w/out-brew: run/anywhere/terminals.md
  docker: run/anywhere/docker.md
  ci-cd: run/anywhere/ci-cd.md
  scripts: run/anywhere/scripts.md
  editors: run/anywhere/editors.md
  pkgx-install: pkgx-install.md
  install: pkgx-install.md
  support: support.md
  dev: dev.md
  help/pkg-not-cached: https://github.com/orgs/pkgxdev/discussions/new?category=help&title=pkg-not-cached
  help/http-failure: https://github.com/orgs/pkgxdev/discussions/new?category=help&title=http-failure
  help/ambiguous-pkgspec: https://github.com/orgs/pkgxdev/discussions/new?category=help&title=ambiguous-pkgspec
