name: CD·docker

on:
  release:
    types:
      - created

concurrency:
  group: docker/${{ github.event.release.tag_name }}
  cancel-in-progress: true

env:
  GHCR_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: docker buildx
        run: |
          for x in $(echo "${{ steps.meta.outputs.tags}}" | tr '\n' ' ');
            do tags="$tags --tag $x";
          done
          docker buildx build \
            --push \
            $tags \
            --platform linux/amd64,linux/arm64 \
            --file Dockerfile \
            .
