name: cd·www

# the binaries for curl tea.xyz/$(uname)/$(uname -m)

on:
  release:
    types:
      - published

concurrency:
  group: cd/www/${{ github.event.release.tag_name }}
  cancel-in-progress: true

jobs:
  www-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.8
        with:
          releaseId: ${{ github.event.release.id }}

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Unpack Binaries
        run: |
          go() {
            tar xJf $1
            mkdir -p out/$2
            tar czf out/$2/$3.tgz tea
            mv tea out/$2/$3
          }

          for filename in tea-*+*+*.tar.xz; do
            case $filename in
            *+darwin+aarch64.tar.xz)
              go $filename Darwin arm64;;
            *+darwin+x86-64.tar.xz)
              go $filename Darwin x86_64;;
            *+linux+aarch64.tar.xz)
              go $filename Linux arm64
              go $filename Linux aarch64;;
            *+linux+x86-64.tar.xz)
              go $filename Linux x86_64;;
            esac
          done

      - name: Upload to S3
        run:
          aws s3 sync out/ s3://www.tea.xyz/
            --metadata-directive REPLACE
            --cache-control "max-age=3600, must-revalidate"

      - name: Invalidate CloudFront
        run:
          aws cloudfront create-invalidation
            --distribution-id ${{ secrets.AWS_CF_DISTRIBUTION_ID }}
            --paths $STATIC_PATHS
        env:
          STATIC_PATHS: >-
            /Darwin/arm64
            /Darwin/x86_64
            /Linux/arm64
            /Linux/aarch64
            /Linux/x86_64
            /Darwin/arm64.tgz
            /Darwin/x86_64.tgz
            /Linux/arm64.tgz
            /Linux/aarch64.tgz
            /Linux/x86_64.tgz
